#requires -Version 7.6
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

<#
.SYNOPSIS
  Scan repo for ponytail: shortcuts and report technical debt / over-engineering.

.DESCRIPTION
  Default mode: scan for ponytail: comments and print debt report.
  -Ledger: output structured debt ledger as markdown.
  -Audit: detect over-engineering patterns (YAGNI, abstraction leaks).

.PARAMETER Ledger
  Output debt ledger markdown (appendable to docs/).

.PARAMETER Audit
  Run over-engineering audit: large skills, comment-heavy scripts.

.PARAMETER Quiet
  Output JSON only (machine-readable).

.PARAMETER Path
  Root path to scan (default: repo root from git).
#>

param(
    [switch]$Ledger,
    [switch]$Audit,
    [switch]$Quiet,
    [string]$Path,
    [ValidateSet('lite','full','ultra','all')]
    [string]$Mode = 'all'
)

if (-not $Path) {
    $gitRoot = & git rev-parse --show-toplevel 2>$null
    if (-not $gitRoot) { throw "Not in a git repo, specify -Path" }
    $Path = $gitRoot
}

$scriptPath = $PSCommandPath

function ShouldSkip {
    param([string]$fullName)
    if ($fullName -eq $scriptPath) { return $true }
    return $fullName -match '\.git\\' -or $fullName -match 'node_modules\\'
}

# === ponytail-debt: scan for ponytail: comments ===
$ponyMatches = @()
$files = Get-ChildItem -Path $Path -Recurse -File -Include "*.ps1", "*.md", "*.psm1"
$files = $files.PSWhere({ -not (ShouldSkip $_.FullName) })
foreach ($f in $files) {
    $content = Get-Content -LiteralPath $f.FullName -Raw -ErrorAction SilentlyContinue
    if (-not $content) { continue }
    $lines = $content -split "`n"
    # Match `ponytail:` (backtick-wrapped in md), # ponytail: (code comments), or ponytail: bare
    $ponyLines = $lines.PSWhere({ $_ -match 'ponytail:' })
    if ($ponyLines.Count -eq 0) { continue }
    foreach ($line in $ponyLines) {
        $lineNum = [Array]::IndexOf($lines, $line) + 1
        # Extract mode prefix: ponytail:lite, ponytail:full, ponytail:ultra, or bare ponytail:
        $tagMode = 'full'  # default
        if ($line -match 'ponytail:(lite|full|ultra)') {
            $tagMode = $matches[1]
        }
        $debt = ($line -replace '.*ponytail:(lite|full|ultra)?\s*', '').Trim()
        # Filter by requested mode
        if ($Mode -ne 'all') {
            if ($tagMode -eq 'lite' -and $Mode -ne 'lite') { continue }
            if ($tagMode -eq 'ultra' -and $Mode -ne 'ultra') { continue }
            if ($tagMode -eq 'full' -and $Mode -notin @('full','ultra')) { continue }
        }
        $isActive = ($f.FullName -notmatch '\\docs\\(archive|research)\\' -and $f.FullName -notmatch '\\.git\\')
        $ponyMatches += [PSCustomObject]@{
            File   = $f.FullName.Replace($Path, '').TrimStart('\')
            Line   = $lineNum
            Debt   = $debt
            Mode   = $tagMode
            Active = $isActive
        }
    }
}

# --- Dedup by filename (junction skills/ → .agents/skills/) ---
$seen = @{}
$deduped = @()
$ponyMatches.PSForEach({
    $key = "$($_.Line):$($_.Debt.Substring(0,[Math]::Min(40,$_.Debt.Length)))"
    if (-not $seen.ContainsKey($key)) {
        $seen[$key] = $true
        # Normalize junction paths
        $_.File = $_.File -replace '^skills\\', '.agents\skills\'
        # AGENTS.md definition lines are not debt
        if ($_.File -match 'AGENTS\.md' -and $_.Line -le 35) {
            $_.Active = $false  # mark as definition, not debt
        }
        $deduped += $_
    }
})
$ponyMatches = $deduped

if ($Quiet) {
    $ponyMatches | ConvertTo-Json -Depth 2
    return
}

# --- Report ---
$active = $ponyMatches.PSWhere({ $_.Active })
$archived = $ponyMatches.PSWhere({ -not $_.Active })

Write-Host "=== Ponytail Debt Report ===" -Fore Cyan
Write-Host "Total ponytail: shortcuts found: $($ponyMatches.Count)  (Mode filter: $Mode)" -Fore Yellow

if ($active.Count -gt 0) {
    Write-Host "`nActive debt items ($($active.Count)):" -Fore Red
    $active | Format-Table File, Line, Mode, @{N='Debt';E={$_.Debt.Substring(0, [Math]::Min(80, $_.Debt.Length))}} -AutoSize
}
if ($archived.Count -gt 0) {
    Write-Host "`nArchived/research items ($($archived.Count)):" -Fore DarkGray
    $archived | Format-Table File, Line, Mode, @{N='Debt';E={$_.Debt.Substring(0, [Math]::Min(80, $_.Debt.Length))}} -AutoSize
}

# --- Ledger output ---
if ($Ledger) {
    $l = @()
    $l += "# Ponytail Debt Ledger"
    $l += ""
    $l += "Auto-generated by ponytail-audit.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    $l += ""
    $l += "## Active Debt"
    $l += ""
    $l += "| File | Line | Mode | Debt | Priority |"
    $l += "|------|------|------|------|----------|"
    if ($active.Count -eq 0) {
        $l += "| (none) | - | - | - | - |"
    } else {
        $active.PSForEach({ $l += "| $($_.File) | $($_.Line) | $($_.Mode) | $($_.Debt) | TBD |" })
    }
    $l += ""
    $l += "## Archived"
    if ($archived.Count -gt 0) {
        $archived.PSForEach({ $l += "- $($_.File):$($_.Line) — $($_.Debt)" })
    }
    Write-Host "`n--- LEDGER OUTPUT ---" -Fore Cyan
    $l -join "`n"
}

# --- Audit: over-engineering patterns ---
if ($Audit) {
    Write-Host "`n=== Over-Engineering Audit ===" -Fore Magenta
    $findings = @()

    # Pattern 1: Skills >5KB
    $skillsDir = Join-Path $Path '.agents\skills'
    if (Test-Path $skillsDir) {
        $largeSkills = (Get-ChildItem -Path $skillsDir -Recurse -Filter "SKILL.md").PSWhere({ $_.Length -gt 5120 })
        if ($largeSkills.Count -gt 0) {
            $findings += "Skills >5KB: $($largeSkills.Count) files"
            $largeSkills.PSForEach({ Write-Host "  ⚠ $($_.FullName.Replace($Path,'').TrimStart('\')) ($($_.Length/1KB -as [int])KB)" -Fore Yellow })
        }
    }

    # Pattern 2: Comment-heavy scripts (>40%)
    $allScripts = (Get-ChildItem -Path $Path -Recurse -File -Include "*.ps1").PSWhere({ -not (ShouldSkip $_.FullName) })
    $denseFiles = @()
    foreach ($s in $allScripts) {
        $content = Get-Content -LiteralPath $s.FullName -ErrorAction SilentlyContinue
        if (-not $content -or $content.Count -lt 10) { continue }
        $commentLines = $content.PSWhere({ $_ -match '^\s*#' -or $_ -match '^\s*<' -or $_ -match '^\s*//' }).Count
        $ratio = $commentLines / $content.Count
        if ($ratio -gt 0.4) {
            $denseFiles += [PSCustomObject]@{ File = $s.FullName.Replace($Path, '').TrimStart('\'); Ratio = "{0:P0}" -f $ratio }
        }
    }
    if ($denseFiles.Count -gt 0) {
        $findings += "Comment-heavy scripts (>40%): $($denseFiles.Count) files"
        $denseFiles.PSForEach({ Write-Host "  ⚠ $($_.File) — $($_.Ratio) comments" -Fore Yellow })
    }

    if ($findings.Count -eq 0) {
        Write-Host "  ✅ No over-engineering patterns detected." -Fore Green
    } else {
        Write-Host "  $($findings.Count) finding(s):" -Fore Yellow
        $findings.PSForEach({ Write-Host "  • $_" })
    }
}
